In [4]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers import Flatten
from keras.datasets import mnist

In [5]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [12]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [25]:
x_train.shape

(60000, 28, 28, 1)

In [13]:
x_train=x_train.reshape(x_train.shape[0],28,28,1).astype('float32')
x_test=x_test.reshape(x_test.shape[0],28,28,1).astype('float32')

In [14]:
x_train=x_train/255
x_test=x_test/255

In [26]:
x_train

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [15]:
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)

In [16]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [17]:
x_test

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [28]:
y_test.shape

(10000, 10)

In [18]:
num_classes=y_test.shape[1]

In [19]:
num_classes

10

In [22]:
def conv():
    model=Sequential()
    model.add(Conv2D(16,(5,5),strides=(1,1),activation='relu',input_shape=(28,28,1)))
    model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
    model.add(Flatten())
    model.add(Dense(100,activation='relu'))
    model.add(Dense(num_classes,activation='Softmax'))
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    return model

In [23]:
model=conv()

In [24]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=200,verbose=2)

Epoch 1/10
300/300 - 9s - loss: 0.3060 - accuracy: 0.9143 - val_loss: 0.1165 - val_accuracy: 0.9659 - 9s/epoch - 30ms/step
Epoch 2/10
300/300 - 8s - loss: 0.0952 - accuracy: 0.9716 - val_loss: 0.0731 - val_accuracy: 0.9769 - 8s/epoch - 26ms/step
Epoch 3/10
300/300 - 8s - loss: 0.0610 - accuracy: 0.9821 - val_loss: 0.0479 - val_accuracy: 0.9847 - 8s/epoch - 27ms/step
Epoch 4/10
300/300 - 8s - loss: 0.0454 - accuracy: 0.9868 - val_loss: 0.0467 - val_accuracy: 0.9847 - 8s/epoch - 27ms/step
Epoch 5/10
300/300 - 8s - loss: 0.0372 - accuracy: 0.9889 - val_loss: 0.0439 - val_accuracy: 0.9853 - 8s/epoch - 28ms/step
Epoch 6/10
300/300 - 8s - loss: 0.0309 - accuracy: 0.9907 - val_loss: 0.0464 - val_accuracy: 0.9843 - 8s/epoch - 28ms/step
Epoch 7/10
300/300 - 8s - loss: 0.0253 - accuracy: 0.9920 - val_loss: 0.0411 - val_accuracy: 0.9875 - 8s/epoch - 28ms/step
Epoch 8/10
300/300 - 8s - loss: 0.0218 - accuracy: 0.9932 - val_loss: 0.0391 - val_accuracy: 0.9879 - 8s/epoch - 26ms/step
Epoch 9/10
300/3

In [29]:
scores=model.evaluate(x_test,y_test,verbose=0)

In [33]:
scores

[0.04012591019272804, 0.9861000180244446]

In [39]:
scores[1]*100

98.61000180244446

In [40]:
print("Accuracy",scores[1]*100)

Accuracy 98.61000180244446
